In [2]:
import numpy as np
data=np.random.randint(0,10,(3,3))

In [2]:
data

In [ ]:
data

In [3]:
data

array([[0, 5, 2],
       [2, 1, 0],
       [7, 0, 8]])

In [ ]:
### array creation functions

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((3))

array([1., 1., 1.])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
### Mathematical functions

In [14]:
data=np.random.randint(0,100,10)

In [15]:
data

array([85, 93,  6, 36, 64, 86, 44, 21, 56, 95])

In [17]:
print(np.sin(data))
print(np.cos(data))
print(np.tan(data))

[-0.17607562 -0.94828214 -0.2794155  -0.99177885  0.92002604 -0.92345845
  0.01770193  0.83665564 -0.521551    0.68326171]
[-0.98437664  0.3174287   0.96017029 -0.12796369  0.39185723 -0.38369844
  0.99984331 -0.54772926  0.85322011  0.73017356]
[ 0.17887017 -2.98738626 -0.29100619  7.75047091  2.34786031  2.40672971
  0.0177047  -1.52749853 -0.61127369  0.93575247]


In [18]:
np.arctan(data)

array([1.55903216, 1.56004405, 1.40564765, 1.54302569, 1.5551726 ,
       1.55916894, 1.54807297, 1.52321322, 1.55294108, 1.5602704 ])

In [19]:
np.arcsin(np.array([1,0.6]))

array([1.57079633, 0.64350111])

In [20]:
data

array([85, 93,  6, 36, 64, 86, 44, 21, 56, 95])

In [21]:
np.log(data)

array([4.44265126, 4.53259949, 1.79175947, 3.58351894, 4.15888308,
       4.4543473 , 3.78418963, 3.04452244, 4.02535169, 4.55387689])

In [ ]:
np.log(data)

In [ ]:
np.log10(data)

In [ ]:
np.log2(data)

In [22]:
np.e

2.718281828459045

In [23]:
import math
np.log(math.pow(2.718281828459045,0.2867))

np.float64(0.2867)

In [24]:
np.float64(0.2867)

np.float64(0.2867)

In [25]:
data1=np.random.randint(0,10,(3,3))
data2=np.random.randint(0,10,(3,3))
data1

array([[1, 5, 4],
       [1, 5, 1],
       [5, 0, 0]])

In [26]:
data2

array([[7, 1, 1],
       [9, 0, 5],
       [6, 5, 4]])

In [27]:
data1+data2

array([[ 8,  6,  5],
       [10,  5,  6],
       [11,  5,  4]])

In [28]:
np.add(data1,data2)

array([[ 8,  6,  5],
       [10,  5,  6],
       [11,  5,  4]])

In [29]:
np.subtract(data1,data2)

array([[-6,  4,  3],
       [-8,  5, -4],
       [-1, -5, -4]])

In [33]:
np.divide(data1,data2)

/tmp/ipython-input-18017515.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(data1,data2)


array([[0.14285714, 5.        , 4.        ],
       [0.11111111,        inf, 0.2       ],
       [0.83333333, 0.        , 0.        ]])

In [31]:
np.multiply(data1,data2)

array([[ 7,  5,  4],
       [ 9,  0,  5],
       [30,  0,  0]])

In [34]:
data1

array([[1, 5, 4],
       [1, 5, 1],
       [5, 0, 0]])

In [35]:
data2

array([[7, 1, 1],
       [9, 0, 5],
       [6, 5, 4]])

In [36]:
np.floor_divide(data1,data2)

/tmp/ipython-input-583036681.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(data1,data2)


array([[0, 5, 4],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
np.ceil_divide(data1,data2)

AttributeError: module 'numpy' has no attribute 'ceil_divide'

In [38]:
data=np.random.randint(0,10,10)/5
print(data)
np.ceil(data)

[0.6 0.8 1.6 0.4 1.4 0.2 1.2 1.6 1.4 0. ]


array([1., 1., 2., 1., 2., 1., 2., 2., 2., 0.])

In [39]:
np.floor(data)

array([0., 0., 1., 0., 1., 0., 1., 1., 1., 0.])

In [ ]:
from logging import log
mathematical:
  airthmetic
  exponential,log
  trigonometrics
  rounding


In [40]:
import numpy as np

In [41]:
data=np.random.randint(0,10,10)
data

array([9, 6, 9, 5, 4, 1, 0, 0, 9, 3])

In [43]:
data>5

array([ True,  True,  True, False, False, False, False, False,  True,
       False])

In [42]:
data[data>5]

array([9, 6, 9, 9])

In [44]:
marks=np.random.randint(10,100,20)
marks

array([22, 97, 68, 12, 42, 44, 67, 96, 46, 40, 88, 59, 87, 67, 57, 51, 56,
       14, 96, 97])

In [45]:
marks[marks<=50]

array([22, 12, 42, 44, 46, 40, 14])

In [46]:
marks[marks<=np.mean(marks)]

array([22, 12, 42, 44, 46, 40, 59, 57, 51, 56, 14])

In [47]:
marks[marks>np.mean(marks)]

array([97, 68, 67, 96, 88, 87, 67, 96, 97])

In [ ]:
### array manipulation

In [ ]:
#function

In [50]:
data=np.random.randint(0,10,(3,3))

In [52]:
data.ravel() #flatining of array

array([6, 7, 8, 3, 2, 0, 8, 4, 6])

In [53]:
data

array([[6, 7, 8],
       [3, 2, 0],
       [8, 4, 6]])

In [55]:
data.T  #it convert rows to column

array([[6, 3, 8],
       [7, 2, 4],
       [8, 0, 6]])

In [56]:
data=np.random.randint(0,10,20)
data.reshape(2,10)     #2*10=20 must have 20

array([[6, 9, 1, 7, 9, 9, 1, 0, 1, 3],
       [3, 1, 7, 5, 8, 2, 8, 2, 1, 6]])

In [58]:
data1=np.random.randint(0,10,(3,3))
data2=np.random.randint(0,10,(3,3))

In [59]:
data1

array([[6, 1, 0],
       [6, 5, 0],
       [6, 1, 8]])

In [60]:
data2

array([[5, 5, 2],
       [1, 8, 4],
       [3, 7, 1]])

In [61]:
np.hstack([data1,data2]) #horizontal stacking/concatination

array([[6, 1, 0, 5, 5, 2],
       [6, 5, 0, 1, 8, 4],
       [6, 1, 8, 3, 7, 1]])

In [62]:
np.vstack([data1,data2])  #vertical stacking or append

array([[6, 1, 0],
       [6, 5, 0],
       [6, 1, 8],
       [5, 5, 2],
       [1, 8, 4],
       [3, 7, 1]])

In [73]:
data=np.random.randint(0,10,10)
np.split(data,5)

[array([5, 7]), array([3, 8]), array([0, 9]), array([0, 8]), array([8, 2])]

In [66]:
matrix=np.array([[1,2,3,4],
                [5,6,7,8]])

In [71]:
np.hsplit(matrix,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [ ]:
matrix=np.array([[1,2,3,4],
                 [5,56,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [76]:
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
 import numpy as np
 df=np.random.randint(0,10,(4,4))
 df

array([[4, 1, 1, 2],
       [5, 5, 0, 7],
       [1, 4, 8, 7],
       [3, 3, 2, 3]])

In [78]:
np.vsplit(df,2)

[array([[4, 1, 1, 2],
        [5, 5, 0, 7]]),
 array([[1, 4, 8, 7],
        [3, 3, 2, 3]])]

In [80]:
np.vsplit(df,4)

[array([[4, 1, 1, 2]]),
 array([[5, 5, 0, 7]]),
 array([[1, 4, 8, 7]]),
 array([[3, 3, 2, 3]])]

In [81]:
np.vsplit(df,1)

[array([[4, 1, 1, 2],
        [5, 5, 0, 7],
        [1, 4, 8, 7],
        [3, 3, 2, 3]])]

In [82]:
df

array([[4, 1, 1, 2],
       [5, 5, 0, 7],
       [1, 4, 8, 7],
       [3, 3, 2, 3]])