In [ ]:
#dummy numpy data
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[60, 50, 46,  4, 31],
       [76, 86, 78,  0, 72],
       [30, 60, 48, 20, 81],
       [93, 22, 70, 49, 58],
       [39, 59, 56,  7, 96]])

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
type(np.array([1,2,3]))

numpy.ndarray

In [ ]:
data

array([[61, 96, 38, 19, 93],
       [17, 34, 23, 66, 89],
       [42, 36, 56, 26, 14],
       [63, 92, 68, 91, 50],
       [37, 17, 84,  3, 99]])

In [ ]:
data[0,0]

np.int64(61)

In [ ]:
data
print(data[-3:1,-3:-1])

[]


In [ ]:
data
print(data[-3:-1,-3:-1])

[[48 20]
 [70 49]]


In [ ]:
print(" ")

In [ ]:
data

array([[60, 50, 46,  4, 31],
       [76, 86, 78,  0, 72],
       [30, 60, 48, 20, 81],
       [93, 22, 70, 49, 58],
       [39, 59, 56,  7, 96]])

In [ ]:
data[-2:-1,-2:-1]

array([[49]])

In [ ]:
x=[1,2,3]    #list
print(type(x))
y=np.array([1,2,3])    #numpy
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
x/2  #in list not airthimatical operation

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2 #numpy support airthmetic opertion

array([0.5, 1. , 1.5])

In [ ]:
x=[1,2,3,]
y=np.array([1,2,3])
#when all the value are integer both returns same result

In [ ]:
x

[1, 2, 3, 6.0]

In [ ]:
y

array([1, 2, 3])

In [ ]:
x=[1,2,3,6.0]
y=np.array([1,2,3,6.0])

In [ ]:
x #list float remain float

[1, 2, 3, 6.0]

In [ ]:
y #in numpy all the elements  becomes all float

array([1., 2., 3., 6.])

In [ ]:
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,6.0,"data"])

In [ ]:
x

[1, 2, 3, 6.0, 'data']

In [ ]:
y #converts every element string

array(['1', '2', '3', '6.0', 'data'], dtype='<U32')

In [ ]:
#perfermance wise numpy better
#numpy carry single datatype

In [ ]:
#inbuilt function

In [ ]:
###random family functions

In [ ]:
np.random.randint(0,100)

57

In [ ]:
np.random.randint(0,100,5)

array([96, 89, 71, 29, 71])

In [ ]:
np.random.randint(0,100,(5,10))

array([[83,  4, 79, 38, 47, 17, 72, 87, 73, 20],
       [79, 69, 63, 91, 98, 24, 96, 70, 69, 39],
       [14, 10, 10, 49, 49, 67, 94, 60, 70, 36],
       [ 6, 78, 11, 51, 61, 58,  6, 75, 57, 76],
       [41, 62, 64, 74, 73,  9, 46, 81, 93, 19]])

In [ ]:
np.random.rand(10)

array([0.58977318, 0.39581622, 0.02798258, 0.06871912, 0.04463068,
       0.50881565, 0.37642198, 0.94737325, 0.54546321, 0.40186121])

In [ ]:
np.random.rand(3,3)

array([[0.35912574, 0.32665827, 0.64124991],
       [0.85633584, 0.79941308, 0.22278294],
       [0.93438774, 0.26520327, 0.5214811 ]])

In [ ]:
data=np.array([1,2,3,4])
data

array([1, 2, 3, 4])

In [ ]:
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])