In [2]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[1, 0, 4],
       [1, 1, 7],
       [4, 1, 1]])

In [3]:
np.random.randn(3,3)

array([[-0.26891497, -1.55978408, -0.01873502],
       [-0.46158363, -2.50592973,  0.09200724],
       [ 1.82703434,  0.06056577, -1.18447995]])

In [4]:
np.random.randn(30,30).std()

np.float64(0.9718259737848453)

In [5]:
np.random.randn(30,30).mean()

np.float64(0.0166684310902666)

In [ ]:
#matrix
np.mean
std
np.var
np.median

In [ ]:
#mean-sum of all elements/total number of elements(numerical value)
#median-taking order if odd then cenetr or even avg of two middle element(numerical)
#mode-most frequented repeated values(categorical like gender)
##mean-when you dont have outlayers
##median-when you have outlayers(real time use)
##mode _data is categorical(gender,countrycode)


In [ ]:
###std-standard_deviation
###variance

In [6]:
import numpy as np
data=np.random.randint(0,5,(3,3))
data

array([[1, 2, 4],
       [3, 3, 0],
       [2, 4, 4]])

In [7]:
data.sum(axis=1 )

array([ 7,  6, 10])

In [8]:
data.max(axis=0)

array([3, 4, 4])

In [9]:
data.min(axis=1)

array([1, 0, 2])

In [10]:
data

array([[1, 2, 4],
       [3, 3, 0],
       [2, 4, 4]])

In [11]:
data[0:2,0:2].max()

np.int64(3)

In [23]:
data=np.random.randint(1,10,10)
data

array([2, 7, 4, 8, 9, 9, 9, 3, 7, 8])

In [19]:
np.int64(1)

np.int64(1)

In [24]:
data.min()

np.int64(2)

In [25]:
data.argmin() #index of min value

np.int64(0)

In [26]:
data.argmax()

np.int64(4)

In [28]:
data=np.random.randint(0,100,(3,3))
#data.argmin(axis=1)
data

array([[ 7,  6, 98],
       [56,  9, 17],
       [23, 19, 34]])

In [32]:
data.argmin(axis=1)

array([1, 1, 1])

In [30]:
data

array([[ 7,  6, 98],
       [56,  9, 17],
       [23, 19, 34]])

In [31]:
data.argmax(axis=1)

array([2, 0, 2])

In [33]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [34]:
retail_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [37]:
retail_data[:,1]

array([25000, 32000, 28000, 41000, 35000, 27000, 39000, 30000, 45000,
       33000])

In [38]:
retail_data[:,1].sum()

np.int64(335000)

In [40]:
retail_data[:,3].max()

np.int64(1800)

In [42]:
retail_data[:,3].argmax()+1

np.int64(9)

In [ ]:
sales/Customers
sales/transaction : basket value
sales/unit :basket size

In [44]:
data=np.random.randint(0,10,3)
x=20

In [45]:
data

array([9, 7, 2])

In [46]:
data+x

array([29, 27, 22])

In [47]:
data

array([9, 7, 2])

In [48]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,1))
x+y

array([[12, 15, 12],
       [ 3,  6, 10],
       [12,  8, 10]])

In [49]:
x

array([[6, 9, 6],
       [0, 3, 7],
       [5, 1, 3]])

In [50]:
y

array([[6],
       [3],
       [7]])

In [51]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(1,3))
x+y

array([[ 9,  7,  8],
       [ 1, 10, 12],
       [ 2, 13, 15]])

In [56]:
x

array([[9, 2, 0],
       [1, 5, 4],
       [2, 8, 7]])

In [57]:
y

array([[0, 5, 8]])

In [60]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))

In [61]:
x

array([[6],
       [6],
       [8]])

In [62]:
y

array([[8, 8, 5]])

In [63]:
x+y

array([[14, 14, 11],
       [14, 14, 11],
       [16, 16, 13]])